[project]
name = "biowell"
id = "your-project-id"

[api]
port = 54321
schemas = ["public"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[functions]
port = 54324
verify_jwt = true
