project_id = "AHMEDBW"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[functions]
port = 54324
