[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package-lock.json"

[build.environment]
  NODE_VERSION = "18"
  # Skip submodule processing since this repo does not use submodules
  GIT_SUBMODULE_STRATEGY = "none"

[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    dataDir = "public/feeds"
    feeds = [
      { name = "hn", url = "https://hnrss.org/frontpage" }
    ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200