[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package-lock.json"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
  feeds = [
    { name = "hn", url = "https://hnrss.org/frontpage" }
  ]