[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package-lock.json"

[build.environment]
  NODE_VERSION = "22"
  PYENV_VERSION = "3.10.13"
  # Skip submodule processing since this repo does not use submodules
  GIT_SUBMODULE_STRATEGY = "none"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200