[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  # Skip submodule processing since this repo does not use submodules
  GIT_SUBMODULE_STRATEGY = "none"

[[plugins]]
  package = "netlify-plugin-fetch-feeds"
  [plugins.inputs]
    dataDir = "public/feeds"
    feeds = [
      { url = "https://hnrss.org/frontpage", file = "hn.xml" }
    ]

